"""Auto-upload module: GitHub Releases + Google Drive."""

import os
import json
import base64
import requests
from datetime import datetime
from pathlib import Path


# ==================== CONFIG ====================
CONFIG_FILE = "upload_config.json"


def load_config():
    """Load config từ file."""
    if not os.path.exists(CONFIG_FILE):
        return {
            "github": {
                "enabled": False,
                "username": "",
                "repo": "",
                "token": "",
                "tag_prefix": "patch",
            },
            "gdrive": {
                "enabled": False,
                "service_account_file": "gdrive_service_account.json",
                "folder_id": "",
            },
            "auto_upload_after_patch": False,
        }
    
    with open(CONFIG_FILE, 'r', encoding='utf-8') as f:
        return json.load(f)


def save_config(config):
    """Save config ra file."""
    with open(CONFIG_FILE, 'w', encoding='utf-8') as f:
        json.dump(config, f, ensure_ascii=False, indent=2)


# ==================== GITHUB ====================
def upload_to_github(file_path, config_github, log_queue=None):
    """Upload file lên GitHub Release.
    
    Returns: (success: bool, url: str or error_msg: str)
    """
    if not config_github.get("enabled"):
        return False, "GitHub upload disabled"
    
    username = config_github.get("username", "").strip()
    repo = config_github.get("repo", "").strip()
    token = config_github.get("token", "").strip()
    tag_prefix = config_github.get("tag_prefix", "patch").strip() or "patch"
    
    if not all([username, repo, token]):
        return False, "GitHub config thiếu username/repo/token"
    
    if not os.path.exists(file_path):
        return False, f"File không tồn tại: {file_path}"
    
    filename = os.path.basename(file_path)
    file_size_mb = os.path.getsize(file_path) / (1024 * 1024)
    
    # Tạo tag với timestamp
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    tag = f"{tag_prefix}-{timestamp}"
    release_name = f"Translation Patch - {datetime.now().strftime('%Y-%m-%d %H:%M')}"
    
    headers = {
        "Authorization": f"token {token}",
        "Accept": "application/vnd.github.v3+json"
    }
    
    if log_queue:
        log_queue.put(f"[INFO] Đang tạo GitHub release với tag: {tag}")
        log_queue.put(f"[INFO] File: {filename} ({file_size_mb:.2f} MB)")
    
    # === Bước 1: Tạo release ===
    try:
        create_url = f"https://api.github.com/repos/{username}/{repo}/releases"
        release_data = {
            "tag_name": tag,
            "name": release_name,
            "body": f"Auto-generated by GFL2 Translation Manager\n\n"
                    f"File: {filename}\n"
                    f"Size: {file_size_mb:.2f} MB\n"
                    f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            "draft": False,
            "prerelease": False
        }
        
        resp = requests.post(create_url, json=release_data, headers=headers, timeout=30)
        if resp.status_code != 201:
            return False, f"Tạo release thất bại ({resp.status_code}): {resp.text[:200]}"
        
        release_id = resp.json()["id"]
        if log_queue:
            log_queue.put(f"[OK] Release created (ID: {release_id})")
        
    except Exception as e:
        return False, f"Lỗi tạo release: {e}"
    
    # === Bước 2: Upload asset ===
    try:
        upload_url = f"https://uploads.github.com/repos/{username}/{repo}/releases/{release_id}/assets"
        params = {"name": filename}
        
        if log_queue:
            log_queue.put(f"[INFO] Đang upload {file_size_mb:.2f} MB...")
        
        with open(file_path, 'rb') as f:
            upload_headers = dict(headers)
            upload_headers["Content-Type"] = "application/octet-stream"
            
            resp = requests.post(
                upload_url,
                params=params,
                headers=upload_headers,
                data=f,
                timeout=300   # 5 phút cho file lớn
            )
        
        if resp.status_code != 201:
            return False, f"Upload asset thất bại ({resp.status_code}): {resp.text[:200]}"
        
        asset_url = resp.json()["browser_download_url"]
        release_url = f"https://github.com/{username}/{repo}/releases/tag/{tag}"
        
        if log_queue:
            log_queue.put(f"[OK] ✅ GitHub upload thành công!")
            log_queue.put(f"[URL] Release: {release_url}")
            log_queue.put(f"[URL] Direct:  {asset_url}")
        
        return True, release_url
    
    except Exception as e:
        return False, f"Lỗi upload asset: {e}"


# ==================== GOOGLE DRIVE ====================
def upload_to_gdrive(file_path, config_gdrive, log_queue=None):
    """Upload file lên Google Drive folder.
    
    Returns: (success: bool, url: str or error_msg: str)
    """
    if not config_gdrive.get("enabled"):
        return False, "Google Drive upload disabled"
    
    sa_file = config_gdrive.get("service_account_file", "").strip()
    folder_id = config_gdrive.get("folder_id", "").strip()
    
    if not sa_file or not os.path.exists(sa_file):
        return False, f"Không tìm thấy Service Account file: {sa_file}"
    
    if not folder_id:
        return False, "Thiếu Folder ID"
    
    if not os.path.exists(file_path):
        return False, f"File không tồn tại: {file_path}"
    
    # Import ở đây để tránh lỗi nếu user không dùng GDrive
    try:
        from google.oauth2 import service_account
        from googleapiclient.discovery import build
        from googleapiclient.http import MediaFileUpload
    except ImportError:
        return False, "Thiếu thư viện. Chạy: pip install google-api-python-client google-auth"
    
    filename = os.path.basename(file_path)
    file_size_mb = os.path.getsize(file_path) / (1024 * 1024)
    
    if log_queue:
        log_queue.put(f"[INFO] Đang upload lên Google Drive...")
        log_queue.put(f"[INFO] File: {filename} ({file_size_mb:.2f} MB)")
    
    try:
        SCOPES = ['https://www.googleapis.com/auth/drive.file']
        creds = service_account.Credentials.from_service_account_file(sa_file, scopes=SCOPES)
        service = build('drive', 'v3', credentials=creds)
        
        # Kiểm tra file trùng tên → xóa file cũ
        query = f"name = '{filename}' and '{folder_id}' in parents and trashed = false"
        existing = service.files().list(q=query, fields="files(id)").execute()
        
        for old_file in existing.get('files', []):
            service.files().delete(fileId=old_file['id']).execute()
            if log_queue:
                log_queue.put(f"[INFO] Đã xóa file cũ có cùng tên")
        
        # Upload file mới
        file_metadata = {
            'name': filename,
            'parents': [folder_id]
        }
        media = MediaFileUpload(file_path, resumable=True)
        
        uploaded = service.files().create(
            body=file_metadata,
            media_body=media,
            fields='id, webViewLink, webContentLink'
        ).execute()
        
        view_url = uploaded.get('webViewLink', '')
        file_id = uploaded.get('id', '')
        
        if log_queue:
            log_queue.put(f"[OK] ✅ Google Drive upload thành công!")
            log_queue.put(f"[URL] View:  {view_url}")
            log_queue.put(f"[ID]  File:  {file_id}")
        
        return True, view_url
    
    except Exception as e:
        return False, f"Lỗi GDrive upload: {e}"


# ==================== WRAPPER ====================
def auto_upload_after_patch(output_file, log_queue=None):
    """Upload file output lên cả GitHub và Google Drive nếu được bật."""
    config = load_config()
    
    results = {
        "github": {"success": False, "url": ""},
        "gdrive": {"success": False, "url": ""},
    }
    
    if not config.get("auto_upload_after_patch"):
        if log_queue:
            log_queue.put("[INFO] Auto-upload disabled.")
        return results
    
    if log_queue:
        log_queue.put("")
        log_queue.put("=" * 60)
        log_queue.put("[UPLOAD] Bắt đầu auto-upload...")
        log_queue.put("=" * 60)
    
    # GitHub
    if config.get("github", {}).get("enabled"):
        if log_queue:
            log_queue.put("")
            log_queue.put("[UPLOAD] → GitHub...")
        success, msg = upload_to_github(output_file, config["github"], log_queue)
        results["github"] = {"success": success, "url": msg if success else ""}
        if not success and log_queue:
            log_queue.put(f"[ERROR] {msg}")
    
    # Google Drive
    if config.get("gdrive", {}).get("enabled"):
        if log_queue:
            log_queue.put("")
            log_queue.put("[UPLOAD] → Google Drive...")
        success, msg = upload_to_gdrive(output_file, config["gdrive"], log_queue)
        results["gdrive"] = {"success": success, "url": msg if success else ""}
        if not success and log_queue:
            log_queue.put(f"[ERROR] {msg}")
    
    if log_queue:
        log_queue.put("")
        log_queue.put("=" * 60)
        log_queue.put("[UPLOAD] Hoàn tất.")
        log_queue.put("=" * 60)
    
    return results


def test_config(log_queue=None):
    """Test config bằng cách upload 1 file dummy nhỏ."""
    import tempfile
    
    config = load_config()
    results = {"github": None, "gdrive": None}
    
    # Tạo file test nhỏ
    with tempfile.NamedTemporaryFile(mode='w', suffix='.txt', delete=False) as f:
        f.write(f"Test upload from GFL2 Translation Manager\n{datetime.now().isoformat()}")
        test_file = f.name
    
    try:
        if config.get("github", {}).get("enabled"):
            if log_queue:
                log_queue.put("[TEST] Testing GitHub...")
            success, msg = upload_to_github(test_file, config["github"], log_queue)
            results["github"] = {"success": success, "msg": msg}
        
        if config.get("gdrive", {}).get("enabled"):
            if log_queue:
                log_queue.put("[TEST] Testing Google Drive...")
            success, msg = upload_to_gdrive(test_file, config["gdrive"], log_queue)
            results["gdrive"] = {"success": success, "msg": msg}
    finally:
        os.unlink(test_file)
    
    return results